server:
  port: 18090

ignore:
  http-urls:
    - /user/login
    - /user/register
    - /user/checkToken

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: backend-search
          uri: lb://backend-search
          predicates:
            - Path=/search/**
        - id: backend-server
          uri: lb://backend-server
          predicates:
            - Path=/favor/**, /user/**, /follow/**, /portal/**
