server:
  port: 18090

ignore:
  http-urls:
    - /user/demo
    - /user/login
    - /user/register
    - /favor/my_collection
    - /follow/my_following

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      # 跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      routes:
        - id: backend-search
          uri: lb://backend-search
          predicates:
            - Path=/paper/**
        - id: backend-server
          uri: lb://backend-server
          predicates:
            - Path=/favor/**, /user/**, /follow/**, /portal/**, /ajax/**
